import Head from "next/head";
import { Poppins } from "next/font/google";
import { Home } from "./Home";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "600"],
  subsets: ["latin"],
});

export default function Index() {
  return (
    <>
      <Head>
        <title>Moelist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Home />
      </main>
    </>
  );
}
